#cloud-config

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install necessary packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker.io
  - docker-compose

# Create monitoring directory
write_files:
  - path: /opt/monitoring/docker-compose.yml
    content: |
      version: "3.8"
      services:
        prometheus:
          image: prom/prometheus
          container_name: prometheus
          restart: unless-stopped
          ports:
            - "9090:9090"
          volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
          command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'

        node-exporter:
          image: prom/node-exporter
          container_name: node-exporter
          restart: unless-stopped
          ports:
            - "9100:9100"
          volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
          command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/rootfs'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

        grafana:
          image: grafana/grafana
          container_name: grafana
          restart: unless-stopped
          ports:
            - "3000:3000"
          volumes:
            - grafana-storage:/var/lib/grafana
          environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false

      volumes:
        prometheus-data:
        grafana-storage:

  - path: /opt/monitoring/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']

# Add Docker's official GPG key and set up the repository
runcmd:
  # Start Docker service
  - systemctl start docker
  - systemctl enable docker

  # Create monitoring directory
  - mkdir -p /opt/monitoring

  # Start the monitoring stack
  - cd /opt/monitoring
  - docker-compose up -d

# Set up automatic start on boot
bootcmd:
  - cd /opt/monitoring && docker-compose up -d 