apiVersion: v1
kind: Service
metadata:
  name: netflix-backend
  namespace: netflix
spec:
  type: NodePort
  selector:
    app: netflix-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080 