kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: netflix-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 30000
    protocol: TCP
  - containerPort: 8081
    hostPort: 8081
    protocol: TCP 