apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend
  namespace: netflix
spec:
  type: NodePort
  selector:
    app: netflix-frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 